service: kafka-service
runtime: custom
env: flex

network:
  name: vpc
  subnetwork_name: vpc
readiness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 5
  success_threshold: 2
  app_start_timeout_sec: 600
resources:
  cpu: 20
  memory_gb: 32
  disk_size_gb: 100
